#!/usr/bin/env python3
"""Turn a prod pg_dump into a single-transaction 'refresh dev' script.

Usage: build_refresh_sql.py <prod.sql> <dev-schema.tsv> <out.sql>

dev-schema.tsv is `table_name<TAB>col,col,col` per line, as produced by the
psql query in refresh-dev-from-prod.sh.

Aborts (exit 1) if prod has a table or column that dev is missing, since the
INSERTs would fail partway. Extra columns in dev are fine and expected --
dev is meant to run ahead of prod.
"""
import re, sys, os

# Parent tables first: the INSERTs run in this order so foreign keys resolve.
ORDER = ['billing_statuses', 'retailers', 'job_types', 'items', 'sub_customers',
         'retailer_job_type_costs', 'shipping_runs', 'packets', 'packet_items',
         'nj_statements', 'nj_payments', 'nj_credit_notes', 'tax_invoices',
         'nj_statement_lines', 'billing_runs', 'id_reports']
UPSERT = {'users'}    # not truncated: profiles.appraiser_id points at it
SKIP   = {'profiles'} # auth-linked; dev keeps its own rows so logins survive
ROWS_PER_INSERT = 50


def unescape(v):
    """Undo pg_dump's COPY text-format escaping."""
    if v == r'\N':
        return None
    out, i = [], 0
    esc = {'t': '\t', 'n': '\n', 'r': '\r', 'b': '\b', 'f': '\f', 'v': '\v', '\\': '\\'}
    while i < len(v):
        if v[i] == '\\' and i + 1 < len(v) and v[i + 1] in esc:
            out.append(esc[v[i + 1]]); i += 2
        else:
            out.append(v[i]); i += 1
    return ''.join(out)


def lit(v):
    # Everything is emitted as a quoted literal; Postgres coerces unknown
    # literals to the target column type on INSERT.
    return 'NULL' if v is None else "'" + v.replace("'", "''") + "'"


def parse_dump(path):
    tables, lines, i = {}, open(path, encoding='utf-8').read().split('\n'), 0
    while i < len(lines):
        m = re.match(r'^COPY public\.(\w+) \((.*?)\) FROM stdin;$', lines[i])
        if m:
            cols = [c.strip() for c in m.group(2).split(',')]
            rows, i = [], i + 1
            while lines[i] != r'\.':
                rows.append([unescape(v) for v in lines[i].split('\t')]); i += 1
            tables[m.group(1)] = (cols, rows)
        i += 1
    return tables


def main():
    src, devschema, out = sys.argv[1], sys.argv[2], sys.argv[3]
    tables = parse_dump(src)

    unknown = set(tables) - (set(ORDER) | UPSERT | SKIP)
    if unknown:
        sys.exit("ABORT: prod has table(s) this script doesn't know how to load: %s\n"
                 "Add them to ORDER in scripts/build_refresh_sql.py, in foreign-key "
                 "order (parents first)." % ', '.join(sorted(unknown)))

    dev = {}
    for line in open(devschema, encoding='utf-8'):
        line = line.rstrip('\n')
        if not line.strip():
            continue
        name, cols = line.split('\t', 1)
        dev[name] = set(c.strip() for c in cols.split(','))

    problems = []
    for t, (cols, _) in tables.items():
        if t not in dev:
            problems.append("  table %s exists in prod but not in dev" % t)
            continue
        missing = set(cols) - dev[t]
        if missing:
            problems.append("  %s is missing column(s): %s" % (t, ', '.join(sorted(missing))))
    if problems:
        sys.exit("ABORT: dev's schema is behind prod's, so the load would fail partway:\n"
                 + "\n".join(problems)
                 + "\n\nApply the missing schema change to dev first, then re-run.")

    setvals = [l.strip() for l in open(src, encoding='utf-8') if "setval('public." in l]

    w = []
    w.append("-- Generated by scripts/build_refresh_sql.py -- do not edit by hand.")
    w.append("-- Source snapshot: %s" % os.path.basename(src))
    w.append("-- One transaction: any error rolls the whole thing back.\n")
    w.append("BEGIN;\n")
    w.append("TRUNCATE TABLE\n" + ",\n".join("  public." + t for t in reversed(ORDER)) + ";\n")

    cols, rows = tables['users']
    w.append("-- Gabby/Paula business rows: upserted rather than truncated, because")
    w.append("-- profiles.appraiser_id references them and dev's profiles are preserved.")
    for r in rows:
        sets = ", ".join("%s = EXCLUDED.%s" % (c, c) for c in cols if c != 'id')
        w.append("INSERT INTO public.users (%s) VALUES (%s)\n  ON CONFLICT (id) DO UPDATE SET %s;"
                 % (", ".join(cols), ", ".join(lit(v) for v in r), sets))

    total = 0
    for t in ORDER:
        cols, rows = tables[t]
        if not rows:
            w.append("\n-- %s: empty in prod" % t)
            continue
        w.append("\n-- %s (%d rows)" % (t, len(rows)))
        head = "INSERT INTO public.%s (%s) VALUES\n" % (t, ", ".join(cols))
        for k in range(0, len(rows), ROWS_PER_INSERT):
            chunk = rows[k:k + ROWS_PER_INSERT]
            w.append(head + ",\n".join("  (" + ", ".join(lit(v) for v in r) + ")"
                                       for r in chunk) + ";")
        total += len(rows)

    w.append("\n-- reset auto-increment sequences")
    w += setvals
    w.append("\nCOMMIT;\n")
    w.append("-- verification")
    w.append("SELECT t.relname AS \"table\",\n"
             "       (xpath('/row/c/text()',\n"
             "              query_to_xml(format('select count(*) as c from public.%I', t.relname),\n"
             "                           false, true, '')))[1]::text AS row_count\n"
             "  FROM pg_class t\n"
             "  JOIN pg_namespace n ON n.oid = t.relnamespace\n"
             " WHERE n.nspname = 'public' AND t.relkind = 'r'\n"
             " ORDER BY 1;")

    open(out, 'w', encoding='utf-8').write("\n".join(w) + "\n")
    print("    %d rows across %d tables" % (total, len([t for t in ORDER if tables[t][1]])))


if __name__ == '__main__':
    main()
